import argparse
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from torch.utils.data import DataLoader

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(BASE_DIR)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from architecture_improved import TinyHybridStudent
from src_replica.loao_train_replica import CAN_FEATURES_16, _load_pair

# Use Captum for SHAP/Integrated Gradients Feature Importance Analysis
try:
    from captum.attr import IntegratedGradients
except ImportError:
    print("Captum not found. Installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "captum"])
    from captum.attr import IntegratedGradients

def set_style():
    sns.set_theme(style="whitegrid", context="paper")
    plt.rcParams.update({
        "font.size": 12,
        "axes.titlesize": 14,
        "axes.labelsize": 10,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "font.family": "serif"
    })

# Wrapped model to isolate CAN input explicitly for Captum
class CanWrapperModel(torch.nn.Module):
    def __init__(self, base_model, eth_stub):
        super().__init__()
        self.base_model = base_model
        self.eth_stub = eth_stub
        
    def forward(self, can_input):
        # We need to duplicate the eth_stub exactly for the current batch size generated by Captum (e.g. 50 steps from baseline)
        b_size = can_input.size(0)
        
        if b_size != self.eth_stub.size(0):
            # Captum interpolates multiples of batch. We repeat the original eth_stub to match.
            # Eth stub was size (original_b_size, ...).
            # IG typically multiplies batch by num_steps. Let's just grab the correct expansion.
            repeat_factor = b_size // self.eth_stub.size(0)
            dims = [1] * self.eth_stub.dim()
            dims[0] = repeat_factor
            expanded_eth = self.eth_stub.repeat(*dims)
            return self.base_model(can_input, expanded_eth)
            
        return self.base_model(can_input, self.eth_stub)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_path", type=str, required=True)
    parser.add_argument("--data_dir", type=str, default="datasets")
    parser.add_argument("--out_dir", type=str, default="reports/paper_figures")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 1. Load sample dataset
    dataset = _load_pair(
        args.data_dir, 
        "can_dos_train.csv", 
        "eth_driving_01_injected_images-003.npy", 
        max_rows=150
    )
    if not dataset:
        print("Dataset failed to load.")
        return
        
    loader = DataLoader(dataset, batch_size=64, shuffle=True)
    batch = next(iter(loader))
    can_t = batch["can"].to(device)
    eth_t = batch["eth"].to(device)
    labels_t = batch["label"].to(device)

    # Filter to only analyze ATTACK samples
    attack_mask = labels_t == 1
    if attack_mask.sum() == 0:
        print("No attack samples in this batch. Exiting.")
        return
        
    can_attacks = can_t[attack_mask]
    eth_attacks = eth_t[attack_mask]

    # 2. Init and Load Model
    model = TinyHybridStudent(
        input_dim=len(CAN_FEATURES_16),
        hidden_dim=32,
        num_classes=2
    ).to(device)
    model.load_state_dict(torch.load(args.model_path, map_location=device))
    model.eval()

    # 3. Apply Integrated Gradients (SHAP proxy)
    ig = IntegratedGradients(CanWrapperModel(model, eth_attacks))
    
    # Baseline for IG: all zeros
    baseline = torch.zeros_like(can_attacks).to(device)
    
    # Calculate attributions targeted at Class 1 (Attack)
    attributions, delta = ig.attribute(can_attacks, baseline, target=1, return_convergence_delta=True)

    # 4. Summarize and Plot
    # Averaged over Batch AND Sequence Window to get global feature importance map
    attr_mean = attributions.mean(dim=0).mean(dim=0).detach().cpu().numpy()
    
    # Normalize absolute magnitude
    attr_abs = np.abs(attr_mean)
    attr_norm = attr_abs / attr_abs.sum()

    # Sort
    sorted_idx = np.argsort(attr_norm)
    sorted_features = [CAN_FEATURES_16[i] for i in sorted_idx]
    sorted_importance = attr_norm[sorted_idx]

    set_style()
    plt.figure(figsize=(10, 6))
    
    # Use diverging colormap
    colors = sns.color_palette("rocket", len(sorted_importance))
    
    plt.barh(sorted_features, sorted_importance, color=colors)
    plt.xlabel("Mean Absolute Attribution (Normalized)")
    plt.title("CAN Feature Importance for Attack Detection (Integrated Gradients)")
    plt.grid(axis='x', alpha=0.3)
    plt.tight_layout()

    out_path = os.path.join(args.out_dir, "shap_feature_importance_replica.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    
    print("\n--- SHAP Feature Attribution ---")
    for f, imp in zip(reversed(sorted_features), reversed(sorted_importance)):
        print(f"  {f}: {imp*100:.1f}%")
        
    print(f"\nSaved feature correlation diagram to: {out_path}")

if __name__ == "__main__":
    main()